apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demoapp
  name: demodep
  namespace: demons
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - image: fitsena/simpleweb:85cdc67a8d36c4d08f332cc5bac82c075e89651f
        imagePullPolicy: Always
        name: demoapp
